### ISSUE TITLE
Detect git branch that clashes with version in `lc release`

### ISSUE THREAD

**Issue by dcorbin** [cisco/elsy#24] opened 2016-11-02 14:23 UTC
If you execute `lc release --version=vx.y.z --git-commit=....`, it's guaranteed to fail if you have a local branch called `vx.y.z`.  But the failure message is not helpful.  Would be nice if lc would check for this, and provide a helpful error message.

**Comment by paulcichonski** [comment] 2016-11-02 14:56
duplicate of #23

**Closed by paulcichonski** 2016-11-02 14:56 UTC
